name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # allows running the job manually at any time
  workflow_dispatch:
  
  # run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a GitHub user (<github_user_name>) contributions graph, output an SVG animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        id: generate_snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Ensure the 'dist' directory exists before running the actions
      - name: Create dist directory
        run: mkdir -p dist
      
      # Use the output from the previous step to determine the file paths
      - name: Move SVG files
        run: |
          mv ${{ steps.generate_snake.outputs.dist }}/github-contribution-grid-snake.svg dist/
          mv ${{ steps.generate_snake.outputs.dist }}/github-contribution-grid-snake-dark.svg dist/
        
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, or as GitHub page
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
